os:
  editCommand: 'floaterm'

keybinding:
  universal:
    return: '<c-/>'

gui:
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeNgColor:
      - underline

git:
  paging:
    colorArg: never
    pager: delta --dark --paging=never
