lastupdatecheck: 0
recentrepos:
- /Users/rochana/repo/rochana-atapattu/dotfiles
- /Users/rochana/repo/prodoscore/development-cluster
- /Users/rochana/repo/codimite/tfaction-template
startuppopupversion: 5
customcommandshistory:
- q
hidecommandlog: false
ignorewhitespaceindiffview: false
