lastupdatecheck: 0
recentrepos:
- /Users/rochana/repo/prodoscore/development-cluster
- /Users/rochana/repo/codimite/tfaction-template
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
